<?php
// Include auth middleware and check if user is employee
require_once '../includes/auth.php';
checkPermission('employee');

$user = getCurrentUser();

// Get user's leave requests for calendar view
require_once '../config/database.php';
try {
    $pdo = getDBConnection();
    $stmt = $pdo->prepare("
        SELECT lr.*, lt.name as leave_type_name
        FROM leave_requests lr
        JOIN leave_types lt ON lr.leave_type_id = lt.id
        WHERE lr.user_id = ? AND lr.status IN ('approved', 'pending', 'rejected')
        ORDER BY lr.start_date
    ");
    $stmt->execute([$user['id']]);
    $leaveRequests = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    $leaveRequests = [];
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leave Calendar - Employee Leave Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../assets/css/calendar.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Leave Management System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard.php">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="apply_leave.php">Apply Leave</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="my_leaves.php">My Leaves</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="calendar.php">Calendar</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-nav ms-auto">
                <span class="navbar-text me-3">Welcome, <?php echo htmlspecialchars($user['first_name'] . ' ' . $user['last_name']); ?> (Employee)</span>
                <a class="nav-link" href="../logout.php">Logout</a>
            </div>
        </div>
    </nav>
    
    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                <h1>Leave Calendar</h1>
                <p>View your approved, pending, and rejected leave requests on a calendar.</p>
            </div>
        </div>
        
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h5 id="current-month-year" class="mb-0"></h5>
                            <div>
                                <button id="prev-month" class="btn btn-outline-secondary btn-sm me-2">&lt; Prev</button>
                                <button id="current-month" class="btn btn-outline-primary btn-sm me-2">Current Month</button>
                                <button id="next-month" class="btn btn-outline-secondary btn-sm">Next &gt;</button>
                            </div>
                        </div>
                        
                        <div class="calendar-container">
                            <div class="calendar-header">
                                <div>Sun</div>
                                <div>Mon</div>
                                <div>Tue</div>
                                <div>Wed</div>
                                <div>Thu</div>
                                <div>Fri</div>
                                <div>Sat</div>
                            </div>
                            <div id="calendar-body" class="calendar-body">
                                <!-- Calendar will be generated by JavaScript -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        <h5 class="mb-0">Calendar Legend</h5>
                    </div>
                    <div class="card-body">
                        <div class="d-flex flex-wrap">
                            <div class="legend-item me-4 mb-2">
                                <span class="legend-color approved"></span>
                                <span>Approved Leave</span>
                            </div>
                            <div class="legend-item me-4 mb-2">
                                <span class="legend-color pending"></span>
                                <span>Pending Leave</span>
                            </div>
                            <div class="legend-item me-4 mb-2">
                                <span class="legend-color rejected"></span>
                                <span>Rejected Leave</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Tooltip for leave details -->
    <div id="tooltip" class="tooltip" style="position: absolute; display: none; background: #333; color: white; padding: 5px 10px; border-radius: 4px; z-index: 1000; font-size: 12px;"></div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        // PHP data to JavaScript
        const leaveRequests = <?php echo json_encode($leaveRequests); ?>;
        const currentUserId = <?php echo $user['id']; ?>;
        const currentUserName = "<?php echo addslashes($user['first_name'] . ' ' . $user['last_name']); ?>";
    </script>
    <script src="../assets/js/calendar.js"></script>
</body>
</html>